name: example-pipeline


steps:
  ingest:
    using: steps.ingest.MyIngestStep
    with:
      location: {{INGEST_DATA_LOCATION}}
      format: {{INGEST_DATA_FORMAT|default('parquet')}}
  
  split:
    using: steps.split.MySplitStep
    with:
      split_ratios: {{SPLIT_RATIOS|default([0.75, 0.125, 0.125])}}
  
  transform:
    using: docker::/my_ml_project/MyTransform
  
  train:
    using: mlflow.pipelines.steps.AutoMLFlaml
    with:
      time_budget_secs: 600
  
  evaluate:
    using: mlflow.pipelines.steps.EvaluateStep
    with:
      validation_criteria:
        - root_mean_squared_error > 10
        - mean_absolute_error < 50
        - weighted_mean_squared_error >=20
  
  register:
    using: mlflow.pipelines.steps.RegisterStep
    with:
      model_name: "taxi_fare_regressor"
      allow_non_validated_model: true
    
metrics:
  primary: "root_mean_squared_error"
  custom: "weighted_mean_squared_error
    using: steps.custom_metrics
